#!/bin/bash

set -e
cd $(cd -P -- "$(dirname -- "$0")" && pwd -P)

. configuration

echo "Generating Jenkinsfile"
sed "s#REPLACE_ATTESTOR_PROJECT_ID#${ATTESTOR_PROJECT_ID}#; \
s#REPLACE_BUILD_ATTESTOR_ID#${BUILD_ATTESTOR_ID}#; \
s#REPLACE_BUILD_ATTESTOR_EMAIL#${BUILD_ATTESTOR_EMAIL}#; \
s#REPLACE_TAG_ATTESTOR_ID#${TAG_ATTESTOR_ID}#; \
s#REPLACE_TAG_ATTESTOR_EMAIL#${TAG_ATTESTOR_EMAIL}#; \
s#REPLACE_DEPLOYER_PROJECT_ID#${DEPLOYER_PROJECT_ID}#; \
s#REPLACE_DEPLOYER_DEV_CLUSTER_NAME#${DEPLOYER_DEV_CLUSTER_NAME}#; \
s#REPLACE_DEPLOYER_DEV_CLUSTER_ZONE#${DEPLOYER_DEV_CLUSTER_ZONE}#; \
s#REPLACE_DEPLOYER_PROD_CLUSTER_NAME#${DEPLOYER_PROD_CLUSTER_NAME}#; \
s#REPLACE_DEPLOYER_PROD_CLUSTER_ZONE#${DEPLOYER_PROD_CLUSTER_ZONE}#; \
s#REPLACE_DEPLOYER_PRODUCTION_NAMESPACE#${DEPLOYER_PRODUCTION_NAMESPACE}#" \
Jenkinsfile.template > ../Jenkinsfile